### ISSUE TITLE
Interfaces for class Landroid/support/v4/util/ArrayMap; not fully resolved

### ISSUE THREAD

**Issue by Aaahh** [testwhat/SmaliEx#13]
12-06 12:44:50:133 De-optimizing /system/app/Bluetooth/Bluetooth.apk
12-06 12:44:51:120 Analysis error in class=Landroid/support/v4/media/MediaMetadataCompat; method=<clinit>
Method: Landroid/support/v4/media/MediaMetadataCompat;-><clinit>()V
Opcode: invoke-virtual-quick
Code address: 19
Near line: 204

12-06 12:44:51:121 org.jf.dexlib2.analysis.AnalysisException: Interfaces for class Landroid/support/v4/util/ArrayMap; not fully resolved
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:222)
    at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:149)
    at org.rh.smaliex.OatUtil$OatDexRewriterModule$1$1.getInstructions(OatUtil.java:478)
    at org.jf.dexlib2.immutable.ImmutableMethodImplementation.of(ImmutableMethodImplementation.java:84)
    at org.jf.dexlib2.immutable.ImmutableMethod.<init>(ImmutableMethod.java:72)
    at org.jf.dexlib2.immutable.ImmutableMethod.of(ImmutableMethod.java:102)
    at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMethod.java:129)
    at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMethod.java:120)
    at org.jf.util.ImmutableConverter$3.next(ImmutableConverter.java:139)
    at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301)
    at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522)
    at com.google.common.collect.ImmutableSortedSet$Builder.addAll(ImmutableSortedSet.java:551)
    at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:326)
    at org.jf.util.ImmutableConverter.toSortedSet(ImmutableConverter.java:137)
    at org.jf.dexlib2.immutable.ImmutableMethod.immutableSetOf(ImmutableMethod.java:116)
    at org.jf.dexlib2.immutable.ImmutableClassDef.<init>(ImmutableClassDef.java:109)
    at org.jf.dexlib2.immutable.ImmutableClassDef.of(ImmutableClassDef.java:149)
    at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableClassDef.java:210)
    at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableClassDef.java:201)
    at org.jf.util.ImmutableConverter$2.next(ImmutableConverter.java:105)
    at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301)
    at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522)
    at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:321)
    at org.jf.util.ImmutableConverter.toSet(ImmutableConverter.java:103)
    at org.jf.dexlib2.immutable.ImmutableClassDef.immutableSetOf(ImmutableClassDef.java:197)
    at org.jf.dexlib2.immutable.ImmutableDexFile.<init>(ImmutableDexFile.java:47)
    at org.jf.dexlib2.immutable.ImmutableDexFile.of(ImmutableDexFile.java:58)
    at org.rh.smaliex.OatUtil$OatDexRewriter.rewriteDexFile(OatUtil.java:431)
    at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:303)
    at org.rh.smaliex.OatUtil.oat2dex(OatUtil.java:159)
    at org.rh.smaliex.Main.mainImpl(Main.java:112)
    at org.rh.smaliex.Main.main(Main.java:53)
Caused by: org.jf.dexlib2.analysis.UnresolvedClassException: Interfaces for class Landroid/support/v4/util/ArrayMap; not fully resolved
    at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.java:209)
    at org.jf.dexlib2.analysis.ClassProto$3.get(ClassProto.java:1063)
    at org.jf.dexlib2.analysis.ClassProto$3.get(ClassProto.java:1030)
    at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
    at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:1026)
    at org.jf.dexlib2.analysis.ClassProto.getMethodByVtableIndex(ClassProto.java:359)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1833)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1035)
    at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:211)
    ... 31 more
Method: Landroid/support/v4/media/MediaMetadataCompat;-><clinit>()V
Opcode: invoke-virtual-quick
Code address: 19
Near line: 204

12-06 12:44:51:122 Failed to re-construct dex java.lang.ClassCastException: org.jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.iface.instruction.formats.Instruction35ms
12-06 12:44:51:123 convertToDex: skip /system/app/Bluetooth/Bluetooth.apk

**Comment by Aaahh** [comment]
ALSO

12-06 12:45:09:937 De-optimizing /system/app/Chrome/Chrome.apk
12-06 12:45:10:162 Analysis error in class=Landroid/support/design/widget/CoordinatorLayout; method=<clinit>
Method: Landroid/support/design/widget/CoordinatorLayout;-><clinit>()V
Opcode: invoke-virtual-quick
Code address: 2
Near line: 88

12-06 12:45:10:164 org.jf.dexlib2.analysis.AnalysisException: Interfaces for class Ljava/lang/Class; not fully resolved
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:222)
	at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:149)
	at org.rh.smaliex.OatUtil$OatDexRewriterModule$1$1.getInstructions(OatUtil.java:478)
	at org.jf.dexlib2.immutable.ImmutableMethodImplementation.of(ImmutableMethodImplementation.java:84)
	at org.jf.dexlib2.immutable.ImmutableMethod.<init>(ImmutableMethod.java:72)
	at org.jf.dexlib2.immutable.ImmutableMethod.of(ImmutableMethod.java:102)
	at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMethod.java:129)
	at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMethod.java:120)
	at org.jf.util.ImmutableConverter$3.next(ImmutableConverter.java:139)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301)
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522)
	at com.google.common.collect.ImmutableSortedSet$Builder.addAll(ImmutableSortedSet.java:551)
	at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSet.java:326)
	at org.jf.util.ImmutableConverter.toSortedSet(ImmutableConverter.java:137)
	at org.jf.dexlib2.immutable.ImmutableMethod.immutableSetOf(ImmutableMethod.java:116)
	at org.jf.dexlib2.immutable.ImmutableClassDef.<init>(ImmutableClassDef.java:109)
	at org.jf.dexlib2.immutable.ImmutableClassDef.of(ImmutableClassDef.java:149)
	at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableClassDef.java:210)
	at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableClassDef.java:201)
	at org.jf.util.ImmutableConverter$2.next(ImmutableConverter.java:105)
	at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:301)
	at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.java:522)
	at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:321)
	at org.jf.util.ImmutableConverter.toSet(ImmutableConverter.java:103)
	at org.jf.dexlib2.immutable.ImmutableClassDef.immutableSetOf(ImmutableClassDef.java:197)
	at org.jf.dexlib2.immutable.ImmutableDexFile.<init>(ImmutableDexFile.java:47)
	at org.jf.dexlib2.immutable.ImmutableDexFile.of(ImmutableDexFile.java:58)
	at org.rh.smaliex.OatUtil$OatDexRewriter.rewriteDexFile(OatUtil.java:431)
	at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:303)
	at org.rh.smaliex.OatUtil.oat2dex(OatUtil.java:159)
	at org.rh.smaliex.Main.mainImpl(Main.java:112)
	at org.rh.smaliex.Main.main(Main.java:53)
Caused by: org.jf.dexlib2.analysis.UnresolvedClassException: Interfaces for class Ljava/lang/Class; not fully resolved
	at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.java:209)
	at org.jf.dexlib2.analysis.ClassProto$3.get(ClassProto.java:1063)
	at org.jf.dexlib2.analysis.ClassProto$3.get(ClassProto.java:1030)
	at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java:125)
	at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:1026)
	at org.jf.dexlib2.analysis.ClassProto.getMethodByVtableIndex(ClassProto.java:359)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:1833)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1035)
	at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:211)
	... 31 more
Method: Landroid/support/design/widget/CoordinatorLayout;-><clinit>()V
Opcode: invoke-virtual-quick
Code address: 2
Near line: 88


12-06 12:45:10:165 Failed to re-construct dex java.lang.ClassCastException: org.jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.iface.instruction.formats.Instruction35ms
12-06 12:45:10:165 convertToDex: skip /system/app/Chrome/Chrome.apk
