### ISSUE TITLE
Sony Xperia D5322 (Droid 5.1.1) deodexing error

### ISSUE THREAD

**Issue by SAMDE22** [testwhat/SmaliEx#15]
System files here - https://cloud.mail.ru/public/AbUa/XsCX2h6r3
Deodexing AnonymousData.apk...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1619219
	at org.jf.dexlib2.dexbacked.BaseDexReader.readUleb128(BaseDexReader.java:101)
	at org.jf.dexlib2.dexbacked.BaseDexReader.readSmallUleb128(BaseDexReader.java:92)
	at org.jf.dexlib2.dexbacked.DexBackedClassDef.<init>(DexBackedClassDef.java:86)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:135)
	at org.jf.dexlib2.dexbacked.DexBackedDexFile$1.readItem(DexBackedDexFile.java:131)
	at org.jf.dexlib2.dexbacked.util.FixedSizeSet$1.next(FixedSizeSet.java:56)
	at org.jf.dexlib2.analysis.ClassPath.addDex(ClassPath.java:113)
	at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:291)
	at org.rh.smaliex.OatUtil.oat2dex(OatUtil.java:159)
	at org.rh.smaliex.Main.mainImpl(Main.java:112)
	at org.rh.smaliex.Main.main(Main.java:53)

**Comment by testwhat** [comment]
The google drive link seems to not public.

**Comment by SAMDE22** [comment]
Public framework.zip - 
https://drive.google.com/file/d/0B8jxACZy2MZMTlVwZFZ3ZURWMEE/view?usp=sharing

**Comment by testwhat** [comment]
Have a try with the latest build on releases page.

**Comment by deluxe-mafia** [comment]
I tried a "snapshot-with-2.1.2", "snapshot" and "oat2dex v0.86", nothing helped. All the time there were errors. Attached is a log. 
[log_decompile.txt](https://github.com/testwhat/SmaliEx/files/233338/log_decompile.txt)

Thanks for your work!
