### ISSUE TITLE
Error while deodex Camera2.apk lollipop 

### ISSUE THREAD

**Issue by imadlatch** [testwhat/SmaliEx#42]
java -Xmx1024M -jar oat2dex.jar Camera2.odex dex
10-07 16:38:59:730 Art version=64 (Camera2.odex)
10-07 16:38:59:745 De-optimizing /system/app/Camera2/Camera2.apk
10-07 16:39:02:489 Analysis error in class=Lcom/bumptech/glide/GenericRequestBuilder$2; method=<clinit>
Method: Lcom/bumptech/glide/GenericRequestBuilder$2;-><clinit>()V
Near line: -1 (address 46)
Instructions:
 [23] sget-object regA=0
 [24] sget-object regA=1
 [25] invoke-virtual-quick regC=1 <-----
 [26] move-result regA=1
 [27] const/4 regA=2

10-07 16:39:02:489 org.jf.dexlib2.analysis.AnalysisException: Could not resolve the method in class unknown at index 15, objReg=1
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(MethodAnalyzer.java:2590)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnalyzer.java:1248)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:259)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:190)
        at org.rh.smaliex.DexUtil$ODexRewriterModule$1$1.getInstructions(DexUtil.java:505)
        ...(Skip 24 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:321)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:244)
        at org.rh.smaliex.OatUtil.oat2dex(OatUtil.java:146)
        at org.rh.smaliex.Main.mainImpl(Main.java:122)
        at org.rh.smaliex.Main.main(Main.java:42)

10-07 16:39:02:521 Failed to re-construct dex java.lang.ClassCastException: org.jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.iface.instruction.formats.Instruction35ms

**Comment by testwhat** [comment]
Please provide boot/odex files.
From "Near line: -1", if the debug/type info is trimmed in build-time, it will be the limitation to deodex.

**Comment by imadlatch** [comment]
I'm trying to deodex Android 6.01 Marshmallow x86_64 and x86 /32bit and 64bit 
here is boot files
https://drive.google.com/open?id=0B8Z9nwDLxu8lbXdvZ0hfYTBReVk

odex files
those Am having issue with
GmsCore
 https://drive.google.com/open?id=0B8Z9nwDLxu8lUXVPQ1ZoZF84Rjg
Camera2
https://drive.google.com/open?id=0B8Z9nwDLxu8lZ1ZMZ1duRzREUXM
chrome
https://drive.google.com/open?id=0B8Z9nwDLxu8lTjZ6c2RvNUtfaGc

**Comment by brainvision** [comment]
I have issue on GmsCore, too, Lollipop 5.1 API 22
