### ISSUE TITLE
Error deodexing htc android 7.0 Dialer.odex

### ISSUE THREAD

**Issue by windxixi** [testwhat/SmaliEx#58]

**Comment by windxixi** [comment]
can not deodex htc d728w services.jar

**Comment by windxixi** [comment]
03-22 21:45:59:749 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:45:59:751 convertToDex: skip /system/framework/ext.jar
03-22 21:45:59:752 De-optimizing /system/framework/framework.jar
03-22 21:46:00:237 Analysis error in class=Landroid/app/AppOpsManager; method=<c
linit>
Method: Landroid/app/AppOpsManager;-><clinit>()V
Near line: 818 (address 1478)
Instructions:
 [734] invoke-static regC=0
 [735] move-result-object regA=3
 [736] invoke-virtual-quick regC=1 regD=2 regE=3 <-----
 [737] add-int/lit8 regA=0 regB=0
 [738] goto

03-22 21:46:00:238 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
the method in class unknown at index 18, objReg=1
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(Meth
odAnalyzer.java:2582)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnaly
zer.java:1271)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:25
9)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:190
)
        at org.rh.smaliex.deopt.OdexRewriter$OdexRewriterModule$1$1.getInstructi
ons(OdexRewriter.java:233)
        ...(Skip 24 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:240 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:46:00:241 convertToDex: skip /system/framework/framework.jar
03-22 21:46:00:242 De-optimizing /system/framework/framework.jar:classes2.dex
03-22 21:46:00:249 Analysis error in class=Landroid/view/View; method=<clinit>
Method: Landroid/view/View;-><clinit>()V
Near line: 705 (address 4)
Instructions:
 [0] const-string regA=9
 [1] sget-object regA=10
 [2] invoke-virtual-quick regC=9 regD=10 <-----
 [3] move-result regA=9
 [4] sput-boolean regA=9

03-22 21:46:00:250 org.jf.dexlib2.analysis.AnalysisException: Interfaces for cla
ss Ljava/lang/String; not fully resolved: Ljava/lang/Comparable;,Ljava/lang/Stri
ng;
        at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.jav
a:296)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:975)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:942)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:933)
        ...(Skip 32 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:251 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:46:00:253 convertToDex: skip /system/framework/framework.jar:classes2.d
ex
03-22 21:46:00:254 De-optimizing /system/framework/telephony-common.jar
03-22 21:46:00:280 Analysis error in class=Lcom/android/internal/telephony/BaseC
ommands; method=<init>
Method: Lcom/android/internal/telephony/BaseCommands;-><init>(Landroid/content/C
ontext;)V
Near line: 58 (address 7)
Instructions:
 [2] invoke-direct regC=3
 [3] sget-object regA=0
 [4] iput-object-quick regA=0 regB=3 <-----
 [5] new-instance regA=0
 [6] invoke-direct regC=0

03-22 21:46:00:281 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
class Lcom/android/internal/telephony/BaseCommands;
        at org.rh.smaliex.deopt.OdexRewriter$ClassPathEx.getClassDef(OdexRewrite
r.java:196)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:93)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:91)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:87)
        ...(Skip 36 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:282 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction22cs
03-22 21:46:00:283 convertToDex: skip /system/framework/telephony-common.jar
03-22 21:46:00:283 De-optimizing /system/framework/voip-common.jar
03-22 21:46:00:365 Output to I:\meizu\728xaudio_camera\system\framework\arm64\oa
t2dex\boot.oat-dex\voip-common.dex
03-22 21:46:00:366 De-optimizing /system/framework/ims-common.jar
03-22 21:46:00:404 Analysis error in class=Lcom/mediatek/ims/internal/DataDispat
cher; method=<clinit>
Method: Lcom/mediatek/ims/internal/DataDispatcher;-><clinit>()V
Near line: 184 (address 63)
Instructions:
 [31] move-result-object regA=2
 [32] const-string regA=3
 [33] invoke-virtual-quick regC=2 regD=3 <-----
 [34] move-result regA=2
 [35] if-eqz regA=2

03-22 21:46:00:405 org.jf.dexlib2.analysis.AnalysisException: Interfaces for cla
ss Ljava/lang/String; not fully resolved: Ljava/lang/Comparable;,Ljava/lang/Stri
ng;
        at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.jav
a:296)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:975)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:942)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:933)
        ...(Skip 32 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:406 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:46:00:408 convertToDex: skip /system/framework/ims-common.jar
03-22 21:46:00:408 De-optimizing /system/framework/mms-common.jar
03-22 21:46:00:415 Output to I:\meizu\728xaudio_camera\system\framework\arm64\oa
t2dex\boot.oat-dex\mms-common.dex
03-22 21:46:00:416 De-optimizing /system/framework/android.policy.jar
03-22 21:46:00:465 Analysis error in class=Lcom/android/internal/policy/impl/Pho
neWindowManager; method=<init>
Method: Lcom/android/internal/policy/impl/PhoneWindowManager;-><init>()V
Near line: 320 (address 7)
Instructions:
 [1] invoke-direct regC=7
 [2] move-result regA=0
 [3] iput-quick regA=0 regB=7 <-----
 [4] const/4 regA=0
 [5] iput-quick regA=0 regB=7

03-22 21:46:00:467 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
class Lcom/android/internal/policy/impl/PhoneWindowManager;
        at org.rh.smaliex.deopt.OdexRewriter$ClassPathEx.getClassDef(OdexRewrite
r.java:196)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:93)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:91)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:87)
        ...(Skip 36 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:468 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction22cs
03-22 21:46:00:468 convertToDex: skip /system/framework/android.policy.jar
03-22 21:46:00:468 De-optimizing /system/framework/apache-xml.jar
03-22 21:46:00:525 Analysis error in class=Lorg/apache/xalan/processor/XSLTSchem
a; method=build
Method: Lorg/apache/xalan/processor/XSLTSchema;->build()V
Near line: 257 (address 743)
Instructions:
 [363] move-object/from16 regA=0 regB=48
 [364] move-object/from16 regA=1 regB=70
 [365] invoke-virtual-quick regC=0 regD=1 <-----
 [366] new-instance regA=49
 [367] const/16 regA=50

03-22 21:46:00:527 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
the method in class unknown at index 41, objReg=0
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInvokeVirtualQuick(Meth
odAnalyzer.java:2582)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnaly
zer.java:1271)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:25
9)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:190
)
        at org.rh.smaliex.deopt.OdexRewriter$OdexRewriterModule$1$1.getInstructi
ons(OdexRewriter.java:233)
        ...(Skip 24 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:527 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:46:00:528 convertToDex: skip /system/framework/apache-xml.jar
03-22 21:46:00:528 De-optimizing /system/framework/HtcLegacy.jar
03-22 21:46:00:548 Output to I:\meizu\728xaudio_camera\system\framework\arm64\oa
t2dex\boot.oat-dex\HtcLegacy.dex
03-22 21:46:00:548 De-optimizing /system/framework/mediatek-common.jar
03-22 21:46:00:612 Output to I:\meizu\728xaudio_camera\system\framework\arm64\oa
t2dex\boot.oat-dex\mediatek-common.dex
03-22 21:46:00:613 De-optimizing /system/framework/mediatek-framework.jar
03-22 21:46:00:673 Analysis error in class=Lcom/mediatek/drm/OmaDrmUtils; method
=<clinit>
Method: Lcom/mediatek/drm/OmaDrmUtils;-><clinit>()V
Near line: 74 (address 45)
Instructions:
 [24] move-result-object regA=0
 [25] const-string regA=3
 [26] invoke-virtual-quick regC=0 regD=3 <-----
 [27] move-result regA=3
 [28] if-nez regA=3

03-22 21:46:00:673 org.jf.dexlib2.analysis.AnalysisException: Interfaces for cla
ss Ljava/lang/String; not fully resolved: Ljava/lang/Comparable;,Ljava/lang/Stri
ng;
        at org.jf.dexlib2.analysis.ClassProto.getDirectInterfaces(ClassProto.jav
a:296)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:975)
        at org.jf.dexlib2.analysis.ClassProto$6.get(ClassProto.java:942)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getVtable(ClassProto.java:933)
        ...(Skip 32 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:675 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction35ms
03-22 21:46:00:675 convertToDex: skip /system/framework/mediatek-framework.jar
03-22 21:46:00:676 De-optimizing /system/framework/mediatek-telephony-common.jar

03-22 21:46:00:680 Output to I:\meizu\728xaudio_camera\system\framework\arm64\oa
t2dex\boot.oat-dex\mediatek-telephony-common.dex
03-22 21:46:00:680 De-optimizing /system/framework/dolby_ds.jar
03-22 21:46:00:693 Analysis error in class=Landroid/dolby/ds/DsAkSettings; metho
d=<clinit>
Method: Landroid/dolby/ds/DsAkSettings;-><clinit>()V
Near line: 530 (address 883)
Instructions:
 [416] sget-object regA=2
 [417] aget-object regA=2 regB=2 regC=0
 [418] iget-object-quick regA=2 regB=2 <-----
 [419] invoke-static regC=0
 [420] move-result-object regA=3

03-22 21:46:00:694 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
class Landroid/dolby/ds/DsAkSettings$ParameterDefn;
        at org.rh.smaliex.deopt.OdexRewriter$ClassPathEx.getClassDef(OdexRewrite
r.java:196)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:93)
        at org.jf.dexlib2.analysis.ClassProto$1.get(ClassProto.java:91)
        at com.google.common.base.Suppliers$MemoizingSupplier.get(Suppliers.java
:125)
        at org.jf.dexlib2.analysis.ClassProto.getClassDef(ClassProto.java:87)
        ...(Skip 36 traces)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:368)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:289)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:155)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

03-22 21:46:00:696 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction22cs
03-22 21:46:00:696 convertToDex: skip /system/framework/dolby_ds.jar

I:\meizu\728xaudio_camera\system\framework\arm64\oat2dex>

**Comment by windxixi** [comment]
I:\meizu\728xaudio_camera\system\framework\arm64\oat2dex>java -jar oat2dex.jar s
ervices.odex dex/
03-22 21:56:18:498 De-optimizing /system/framework/services.jar
03-22 21:56:19:043 Analysis error in class=Lcom/android/server/CountryDetectorSe
rvice$Receiver; method=equals
Method: Lcom/android/server/CountryDetectorService$Receiver;->equals(Ljava/lang/
Object;)Z
Opcode: iget-object-quick
Code address: 8
Near line: 71

03-22 21:56:19:045 org.jf.dexlib2.analysis.AnalysisException: Could not resolve
the field in class Ljava/lang/Object; at offset 8 in equals
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeIputIgetQuick(MethodAna
lyzer.java:1715)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyzeInstruction(MethodAnaly
zer.java:1032)
        at org.jf.dexlib2.analysis.MethodAnalyzer.analyze(MethodAnalyzer.java:21
1)
        at org.jf.dexlib2.analysis.MethodAnalyzer.<init>(MethodAnalyzer.java:149
)
        at org.rh.smaliex.OatUtil$OatDexRewriterModule$1$1.getInstructions(OatUt
il.java:478)
        at org.jf.dexlib2.immutable.ImmutableMethodImplementation.of(ImmutableMe
thodImplementation.java:84)
        at org.jf.dexlib2.immutable.ImmutableMethod.<init>(ImmutableMethod.java:
72)
        at org.jf.dexlib2.immutable.ImmutableMethod.of(ImmutableMethod.java:102)

        at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMet
hod.java:129)
        at org.jf.dexlib2.immutable.ImmutableMethod$1.makeImmutable(ImmutableMet
hod.java:120)
        at org.jf.util.ImmutableConverter$3.next(ImmutableConverter.java:139)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(Immutabl
eCollection.java:301)
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.ja
va:522)
        at com.google.common.collect.ImmutableSortedSet$Builder.addAll(Immutable
SortedSet.java:551)
        at com.google.common.collect.ImmutableSortedSet.copyOf(ImmutableSortedSe
t.java:326)
        at org.jf.util.ImmutableConverter.toSortedSet(ImmutableConverter.java:13
7)
        at org.jf.dexlib2.immutable.ImmutableMethod.immutableSetOf(ImmutableMeth
od.java:116)
        at org.jf.dexlib2.immutable.ImmutableClassDef.<init>(ImmutableClassDef.j
ava:110)
        at org.jf.dexlib2.immutable.ImmutableClassDef.of(ImmutableClassDef.java:
149)
        at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableC
lassDef.java:210)
        at org.jf.dexlib2.immutable.ImmutableClassDef$3.makeImmutable(ImmutableC
lassDef.java:201)
        at org.jf.util.ImmutableConverter$2.next(ImmutableConverter.java:105)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(Immutabl
eCollection.java:301)
        at com.google.common.collect.ImmutableSet$Builder.addAll(ImmutableSet.ja
va:522)
        at com.google.common.collect.ImmutableSet.copyOf(ImmutableSet.java:321)
        at org.jf.util.ImmutableConverter.toSet(ImmutableConverter.java:103)
        at org.jf.dexlib2.immutable.ImmutableClassDef.immutableSetOf(ImmutableCl
assDef.java:197)
        at org.jf.dexlib2.immutable.ImmutableDexFile.<init>(ImmutableDexFile.jav
a:47)
        at org.jf.dexlib2.immutable.ImmutableDexFile.of(ImmutableDexFile.java:58
)
        at org.rh.smaliex.OatUtil$OatDexRewriter.rewriteDexFile(OatUtil.java:431
)
        at org.rh.smaliex.OatUtil.convertToDex(OatUtil.java:303)
        at org.rh.smaliex.OatUtil.oat2dex(OatUtil.java:159)
        at org.rh.smaliex.Main.mainImpl(Main.java:112)
        at org.rh.smaliex.Main.main(Main.java:53)
Method: Lcom/android/server/CountryDetectorService$Receiver;->equals(Ljava/lang/
Object;)Z
Opcode: iget-object-quick
Code address: 8
Near line: 71


03-22 21:56:19:047 Failed to re-construct dex java.lang.ClassCastException: org.
jf.dexlib2.analysis.UnresolvedOdexInstruction cannot be cast to org.jf.dexlib2.i
face.instruction.formats.Instruction22cs
03-22 21:56:19:048 convertToDex: skip /system/framework/services.jar

I:\meizu\728xaudio_camera\system\framework\arm64\oat2dex>

**Comment by windxixi** [comment]
the files:
https://drive.google.com/open?id=133EAPjSwoU6OTLgZ7cKriO7FmTxxxKxx

**Comment by testwhat** [comment]
The files from the link do not contain any oat files for deodex.
And please try 0.86 or last pre-release.
