### ISSUE TITLE
can't handle android 8.0?

### ISSUE THREAD

**Issue by jiok** [testwhat/SmaliEx#62]
java -jar oat2dex.jar boot framework/arm64/boot.oat
Exception in thread "main" java.lang.IllegalArgumentException
        at java.nio.Buffer.position(Unknown Source)
        at org.rh.smaliex.reader.DataReader.position(DataReader.java:61)
        at org.rh.smaliex.reader.DataReader.seek(DataReader.java:57)
        at org.rh.smaliex.reader.Oat.<init>(Oat.java:210)
        at org.rh.smaliex.OatUtil.getOat(OatUtil.java:91)
        at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:190)
        at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:75)
        at org.rh.smaliex.Main.mainImpl(Main.java:106)
        at org.rh.smaliex.Main.main(Main.java:43)

**Comment by yy4020** [comment]
> java -jar oat2dex.jar boot framework/arm64/boot.oat
> Exception in thread "main" java.lang.IllegalArgumentException
> at java.nio.Buffer.position(Unknown Source)
> at org.rh.smaliex.reader.DataReader.position(DataReader.java:61)
> at org.rh.smaliex.reader.DataReader.seek(DataReader.java:57)
> at org.rh.smaliex.reader.Oat.(Oat.java:210)
> at org.rh.smaliex.OatUtil.getOat(OatUtil.java:91)
> at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:190)
> at org.rh.smaliex.OatUtil.bootOat2Dex(OatUtil.java:75)
> at org.rh.smaliex.Main.mainImpl(Main.java:106)
> at org.rh.smaliex.Main.main(Main.java:43)

you can try lastest version  oat2dex.jar released on 4 Jun 2018. The dowload address is [https://github.com/testwhat/SmaliEx/releases/tag/snapshot ](url)
I use the lastest version oat2dex.jar can handle huawei mate9( android 8.0).
cmd:
 ` java -jar oat2dex.jar boot system\framework\arm64`
