### ISSUE TITLE
The tool throws an exception when executing 'java -jar oat2dd.jar devfw'

### ISSUE THREAD

**Issue by Flowertome** [testwhat/SmaliEx#66]
➜  smaliex-bin git:(master) java -jar oat2dex.jar devfw
11-23 05:05:11:395 Preparing boot jars from nubia-nx627j-0123456789ABCDEF
11-23 05:05:11:464 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-QPerformance.art.rel, skip pull boot-QPerformance.art.rel
11-23 05:05:11:464 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-QPerformance.oat, skip pull boot-QPerformance.oat
11-23 05:05:11:464 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-QPerformance.vdex, skip pull boot-QPerformance.vdex
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-UxPerformance.art.rel, skip pull boot-UxPerformance.art.rel
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-UxPerformance.oat, skip pull boot-UxPerformance.oat
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-UxPerformance.vdex, skip pull boot-UxPerformance.vdex
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-WfdCommon.art.rel, skip pull boot-WfdCommon.art.rel
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-WfdCommon.oat, skip pull boot-WfdCommon.oat
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-WfdCommon.vdex, skip pull boot-WfdCommon.vdex
11-23 05:05:11:465 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.base-V1.0-java.art.rel, skip pull boot-android.hidl.base-V1.0-java.art.rel
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.base-V1.0-java.oat, skip pull boot-android.hidl.base-V1.0-java.oat
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.base-V1.0-java.vdex, skip pull boot-android.hidl.base-V1.0-java.vdex
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.manager-V1.0-java.art.rel, skip pull boot-android.hidl.manager-V1.0-java.art.rel
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.manager-V1.0-java.oat, skip pull boot-android.hidl.manager-V1.0-java.oat
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.hidl.manager-V1.0-java.vdex, skip pull boot-android.hidl.manager-V1.0-java.vdex
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.test.base.art.rel, skip pull boot-android.test.base.art.rel
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.test.base.oat, skip pull boot-android.test.base.oat
11-23 05:05:11:466 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-android.test.base.vdex, skip pull boot-android.test.base.vdex
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-apache-xml.art.rel, skip pull boot-apache-xml.art.rel
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-apache-xml.oat, skip pull boot-apache-xml.oat
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-apache-xml.vdex, skip pull boot-apache-xml.vdex
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-bouncycastle.art.rel, skip pull boot-bouncycastle.art.rel
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-bouncycastle.oat, skip pull boot-bouncycastle.oat
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-bouncycastle.vdex, skip pull boot-bouncycastle.vdex
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-com.qualcomm.qti.camera.art.rel, skip pull boot-com.qualcomm.qti.camera.art.rel
11-23 05:05:11:467 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-com.qualcomm.qti.camera.oat, skip pull boot-com.qualcomm.qti.camera.oat
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-com.qualcomm.qti.camera.vdex, skip pull boot-com.qualcomm.qti.camera.vdex
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-conscrypt.art.rel, skip pull boot-conscrypt.art.rel
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-conscrypt.oat, skip pull boot-conscrypt.oat
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-conscrypt.vdex, skip pull boot-conscrypt.vdex
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-libart.art.rel, skip pull boot-core-libart.art.rel
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-libart.oat, skip pull boot-core-libart.oat
11-23 05:05:11:468 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-libart.vdex, skip pull boot-core-libart.vdex
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-oj.art.rel, skip pull boot-core-oj.art.rel
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-oj.oat, skip pull boot-core-oj.oat
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-core-oj.vdex, skip pull boot-core-oj.vdex
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ext.art.rel, skip pull boot-ext.art.rel
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ext.oat, skip pull boot-ext.oat
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ext.vdex, skip pull boot-ext.vdex
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework-oahl-backward-compatibility.art.rel, skip pull boot-framework-oahl-backward-compatibility.art.rel
11-23 05:05:11:469 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework-oahl-backward-compatibility.oat, skip pull boot-framework-oahl-backward-compatibility.oat
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework-oahl-backward-compatibility.vdex, skip pull boot-framework-oahl-backward-compatibility.vdex
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework.art.rel, skip pull boot-framework.art.rel
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework.oat, skip pull boot-framework.oat
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-framework.vdex, skip pull boot-framework.vdex
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-gesture.art.rel, skip pull boot-gesture.art.rel
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-gesture.oat, skip pull boot-gesture.oat
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-gesture.vdex, skip pull boot-gesture.vdex
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ifaa_fingerprint.art.rel, skip pull boot-ifaa_fingerprint.art.rel
11-23 05:05:11:470 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ifaa_fingerprint.oat, skip pull boot-ifaa_fingerprint.oat
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ifaa_fingerprint.vdex, skip pull boot-ifaa_fingerprint.vdex
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ims-common.art.rel, skip pull boot-ims-common.art.rel
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ims-common.oat, skip pull boot-ims-common.oat
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-ims-common.vdex, skip pull boot-ims-common.vdex
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubia-vibrate.art.rel, skip pull boot-nubia-vibrate.art.rel
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubia-vibrate.oat, skip pull boot-nubia-vibrate.oat
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubia-vibrate.vdex, skip pull boot-nubia-vibrate.vdex
11-23 05:05:11:471 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubiatel-common.art.rel, skip pull boot-nubiatel-common.art.rel
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubiatel-common.oat, skip pull boot-nubiatel-common.oat
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-nubiatel-common.vdex, skip pull boot-nubiatel-common.vdex
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-okhttp.art.rel, skip pull boot-okhttp.art.rel
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-okhttp.oat, skip pull boot-okhttp.oat
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-okhttp.vdex, skip pull boot-okhttp.vdex
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-tcmiface.art.rel, skip pull boot-tcmiface.art.rel
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-tcmiface.oat, skip pull boot-tcmiface.oat
11-23 05:05:11:472 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-tcmiface.vdex, skip pull boot-tcmiface.vdex
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-common.art.rel, skip pull boot-telephony-common.art.rel
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-common.oat, skip pull boot-telephony-common.oat
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-common.vdex, skip pull boot-telephony-common.vdex
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-ext.art.rel, skip pull boot-telephony-ext.art.rel
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-ext.oat, skip pull boot-telephony-ext.oat
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-ext.vdex, skip pull boot-telephony-ext.vdex
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-static-config.art.rel, skip pull boot-telephony-static-config.art.rel
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-static-config.oat, skip pull boot-telephony-static-config.oat
11-23 05:05:11:473 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-telephony-static-config.vdex, skip pull boot-telephony-static-config.vdex
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-voip-common.art.rel, skip pull boot-voip-common.art.rel
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-voip-common.oat, skip pull boot-voip-common.oat
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot-voip-common.vdex, skip pull boot-voip-common.vdex
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot.art.rel, skip pull boot.art.rel
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot.oat, skip pull boot.oat
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-raw/boot.vdex, skip pull boot.vdex
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/qcom.fmradio.jar, skip pull /system/framework/qcom.fmradio.jar
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/com.qualcomm.qti.camera.jar, skip pull /system/framework/com.qualcomm.qti.camera.jar
11-23 05:05:11:474 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/QPerformance.jar, skip pull /system/framework/QPerformance.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/UxPerformance.jar, skip pull /system/framework/UxPerformance.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/core-oj.jar, skip pull /system/framework/core-oj.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/core-libart.jar, skip pull /system/framework/core-libart.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/conscrypt.jar, skip pull /system/framework/conscrypt.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/okhttp.jar, skip pull /system/framework/okhttp.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/bouncycastle.jar, skip pull /system/framework/bouncycastle.jar
11-23 05:05:11:475 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/apache-xml.jar, skip pull /system/framework/apache-xml.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/ext.jar, skip pull /system/framework/ext.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/framework.jar, skip pull /system/framework/framework.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/telephony-common.jar, skip pull /system/framework/telephony-common.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/voip-common.jar, skip pull /system/framework/voip-common.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/ims-common.jar, skip pull /system/framework/ims-common.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/android.hidl.base-V1.0-java.jar, skip pull /system/framework/android.hidl.base-V1.0-java.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/android.hidl.manager-V1.0-java.jar, skip pull /system/framework/android.hidl.manager-V1.0-java.jar
11-23 05:05:11:476 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/framework-oahl-backward-compatibility.jar, skip pull /system/framework/framework-oahl-backward-compatibility.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/android.test.base.jar, skip pull /system/framework/android.test.base.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/tcmiface.jar, skip pull /system/framework/tcmiface.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/telephony-ext.jar, skip pull /system/framework/telephony-ext.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/WfdCommon.jar, skip pull /system/framework/WfdCommon.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/ifaa_fingerprint.jar, skip pull /system/framework/ifaa_fingerprint.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/nubiatel-common.jar, skip pull /system/framework/nubiatel-common.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/nubia-vibrate.jar, skip pull /system/framework/nubia-vibrate.jar
11-23 05:05:11:477 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/telephony-static-config.jar, skip pull /system/framework/telephony-static-config.jar
11-23 05:05:11:478 Found /home/flowertome/SmaliEx/smaliex-bin/boot-jar-original/gesture.jar, skip pull /system/framework/gesture.jar
11-23 05:05:11:491 java.lang.IllegalArgumentException
	at java.nio.Buffer.position(Buffer.java:244)
	at org.rh.smaliex.reader.DataReader.position(DataReader.java:61)
	at org.rh.smaliex.reader.DataReader.seek(DataReader.java:57)
	at org.rh.smaliex.reader.Oat.<init>(Oat.java:210)
	at org.rh.smaliex.OatUtil.getOat(OatUtil.java:91)
	at org.rh.smaliex.OatUtil.convertDexFromBootOat(OatUtil.java:190)
	at org.rh.smaliex.OatUtil.bootOat2Jar(OatUtil.java:63)
	at org.rh.smaliex.DeodexFrameworkFromDevice.generateBootJar(DeodexFrameworkFromDevice.java:373)
	at org.rh.smaliex.DeodexFrameworkFromDevice.deOptimizeFramework(DeodexFrameworkFromDevice.java:263)
	at org.rh.smaliex.DeodexFrameworkFromDevice$1.run(DeodexFrameworkFromDevice.java:79)
	at org.rh.smaliex.AdbUtil$2.deviceConnected(AdbUtil.java:161)
	at com.android.ddmlib.AndroidDebugBridge.deviceConnected(AndroidDebugBridge.java:678)
	at com.android.ddmlib.DeviceMonitor.updateDevices(DeviceMonitor.java:148)
	at com.android.ddmlib.DeviceMonitor.access$300(DeviceMonitor.java:40)
	at com.android.ddmlib.DeviceMonitor$DeviceListUpdateListener.deviceListUpdate(DeviceMonitor.java:230)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.processIncomingDeviceData(DeviceMonitor.java:417)
	at com.android.ddmlib.DeviceMonitor$DeviceListMonitorTask.run(DeviceMonitor.java:353)
	at java.lang.Thread.run(Thread.java:748)

**Comment by LamBooFly** [comment]
我也遇到这样求解决
